######################################################################
# Automatically generated by qmake (2.01a) Di. Jul 20 21:26:15 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../src/uml/attribute.h \
           ../src/uml/visibility.h \
           ../src/uml/multiplicity.h \
           testumlattribute.moc
SOURCES += testumlattribute.cpp \
           ../src/uml/attribute.cpp \
           ../src/uml/visibility.cpp \
           ../src/uml/multiplicity.cpp
