# #####################################################################
# Automatically generated by qmake (2.01a) Di. Jul 20 21:26:15 2010
# #####################################################################
CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += uml/testumlclass.h \
    uml/testumlparameter.h \
    uml/testumlvisibility.h \
    uml/testumlmultiplicity.h \
    uml/testumlattribute.h \
    ../src/uml/class.h \
    ../src/uml/parameter.h \
    ../src/uml/attribute.h \
    ../src/uml/visibility.h \
    ../src/uml/multiplicity.h \
    ../src/uml/exceptions.h \
    ../src/uml/method.h
SOURCES += uml/testumlclass.cpp \
    uml/testumlparameter.cpp \
    uml/testumlvisibility.cpp \
    tests.cpp \
    uml/testumlmultiplicity.cpp \
    uml/testumlattribute.cpp \
    ../src/uml/class.cpp \
    ../src/uml/parameter.cpp \
    ../src/uml/attribute.cpp \
    ../src/uml/visibility.cpp \
    ../src/uml/multiplicity.cpp \
    ../src/uml/method.cpp
