######################################################################
# Automatically generated by qmake (2.01a) Do. Jul 15 15:31:13 2010
######################################################################

TEMPLATE = app
TARGET = atuml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += atuml.h atumlsettingsprovider.h
SOURCES += atuml.cpp main.cpp atumlsettingsprovider.cpp
